### ISSUE TITLE
Support for reading Excel,Properties,csv,txt files.

### ISSUE THREAD

**Issue by mfaisalkhatri** [WasiqB/coteafs-config#4]
Need support to read the following files :
01. Excel
02. Properties
03. csv
04. txt

**Comment by WasiqB** [comment]
Good suggestions!
Can you create separate issues for each type so it will serve in tracking the development.

**Comment by WasiqB** [comment]
I'm not sure how a user will feed his config values in txt file? @mfaisalkhatri , please provide more details about how will the config format will look like?

**Comment by mfaisalkhatri** [comment]
Ok, than this issue will be for reading Excel file only.

**Comment by mfaisalkhatri** [comment]
i am closing this issue, will post 4 new issue with different file types.
