### ISSUE TITLE
Support for Excel File.

### ISSUE THREAD

**Issue by mfaisalkhatri** [WasiqB/coteafs-config#6]
Need to provide support for reading xls, xlsx files.

**Comment by WasiqB** [comment]
Can you describe the expected behavior and the format of the config file in xls?

**Comment by mfaisalkhatri** [comment]
xls file will be in Excel 97-2000 format.

**Comment by WasiqB** [comment]
Format I mean, how the config values in the columns will be displayed for the config file.
* Vertical column similar to properties file.
* Horizontal column like typical table in excel.

Also provide a sample file.

**Comment by mfaisalkhatri** [comment]
I think we should drop this out, as it might be rarely used, also, we already have xtesy repo for reading excel file.

**Comment by WasiqB** [comment]
So closing this issue. Will take this file format for data provider project.
