### ISSUE TITLE
Support for csv file.

### ISSUE THREAD

**Issue by mfaisalkhatri** [WasiqB/coteafs-config#8]
Need to provide support to read csv.config file.

**Comment by WasiqB** [comment]
Please provide sample CSV config file.

**Comment by mfaisalkhatri** [comment]
Mistakenly put csv.config, this is not for config file. It is for using csv file like dataProvider.

**Comment by WasiqB** [comment]
Then it's out of scope. We will create new project for data providers. Closing this issue.
