### ISSUE TITLE
Support for txt file.

### ISSUE THREAD

**Issue by mfaisalkhatri** [WasiqB/coteafs-config#9]
Need to provide support to read txt config file.

Data in the file might come in any one format:
01. Pipe Separated.
02. Tab Separated.

**Comment by WasiqB** [comment]
Please provide sample TXT config file.

**Comment by mfaisalkhatri** [comment]
Same case like that of csv, this is also dataProvider file.

**Comment by WasiqB** [comment]
Closing this issue as the required functionality will be handled in a new project.
